server:
  port: ${PORT:8085}

spring:
  application:
    name: friendship-service

  # ======================
  # DATABASE (PostgreSQL)
  # ======================
  datasource:
    url: ${FRIENDSHIP_DATABASE_URL:jdbc:postgresql://localhost:5436/friendship_service}
    username: ${FRIENDSHIP_DATABASE_USER:friendship_user}
    password: ${FRIENDSHIP_DATABASE_PASSWORD:friendship_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: friendship-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


# ======================
# ACTUATOR
# ======================
management:
  endpoints:
    web:
      exposure:
        include: health,info


common:
  security:
    cors:
      allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:3000}"
      allowed-methods: "*"
      allowed-headers: "*"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId}]"

services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8082}