server:
  port: ${PORT:8086}

spring:
  application:
    name: notification-service

  # ======================
  # DATABASE (PostgreSQL)
  # ======================
  datasource:
    url: ${NOTIFICATION_DATABASE_URL:jdbc:postgresql://localhost:5435/notification_service}
    username: ${NOTIFICATION_DATABASE_USER:notification_user}
    password: ${NOTIFICATION_DATABASE_PASSWORD:notification_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}

  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 3s

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.common.kafka.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true


# ======================
# ACTUATOR
# ======================
management:
  endpoints:
    web:
      exposure:
        include: health,info


common:
  security:
    cors:
      allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}"
      allowed-methods: "*"
      allowed-headers: "*"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId}]"
